apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wallet-service-db-cpu-scaler
  namespace: project  
spec:
  maxReplicas: 4 # maximum replicas of pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wallet-service-db # TARGET name of the deployment the autoscaler need to be run on
  targetCPUUtilizationPercentage: 30 # CPU maximum amount of use on the pod is set to 30%.
