# db-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallet-service-postgres-data-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: project
    name: wallet-service-postgres-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/projects/easypay-postgres-data-prod"

