apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  type: NodePort
  selector:
    app: wallet-service
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: "https"
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30001
