apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-admin-role-rolebinding
  namespace: project
subjects:
- kind: User
  name: pod-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-admin-role
  apiGroup: rbac.authorization.k8s.io
