apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallet-service-source-code-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: project
    name: wallet-service-source-code-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/projects/wallet-service"
